### ISSUE TITLE
Installation from the Moodle plugin page doesn't work

### ISSUE THREAD

**Issue by mattgig** [mihuasi/moodle-mod_goodhabits#4]
In Moodle 3.11.1 (PHP 7.3) when you download the ZIP file from the plugin directory and try to install it you get an error:

Install plugin from ZIP file
Validating mod_goodhabits ... Error
  [Error] Extracted file not found [{"file":"goodhabits\/.git\/objects\/info\/"}] 
Installation aborted due to validation failure

**Comment by mihuasi** [comment]
Hi,

Thanks for reporting this. I will have a look into it (though on holiday at the moment so might be a few weeks).

If you are able to delete the .git directory, it should install ok but I haven't seen this issue before.

**Comment by mattgig** [comment]
Deleting the .git directory solved the problem.
